definitions:
  model.Answer:
    properties:
      id:
        type: string
      isCorrect:
        type: boolean
      questionID:
        type: string
      text:
        type: string
    type: object
  model.Question:
    properties:
      id:
        type: string
      quizID:
        type: string
      text:
        type: string
    type: object
  model.Quiz:
    properties:
      id:
        type: string
      inviteCode:
        type: string
      name:
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      iconUrl:
        type: string
      id:
        type: string
      isGuest:
        type: boolean
      quizID:
        type: string
      username:
        type: string
    type: object
  restapi.CreateAnswerRequest:
    properties:
      iscorrect:
        type: boolean
      question_id:
        type: string
      text:
        type: string
    required:
    - question_id
    - text
    type: object
  restapi.CreateQuestionRequest:
    properties:
      quiz_id:
        type: string
      text:
        type: string
    required:
    - quiz_id
    - text
    type: object
  restapi.CreateQuizRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  restapi.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  restapi.RegisterRequest:
    properties:
      email:
        type: string
      iconurl:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - iconurl
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /api/answers:
    get:
      consumes:
      - application/json
      description: Retrieve all answers belonging to a specific question
      parameters:
      - description: Question ID
        in: query
        name: question_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Answer'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - CookieAuth: []
      summary: Get all answers for a question
      tags:
      - answer
  /api/answers/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve an answer using its unique ID
      parameters:
      - description: Answer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Answer'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - CookieAuth: []
      summary: Get an answer by ID
      tags:
      - answer
  /api/create-answer:
    post:
      consumes:
      - application/json
      description: Create an answer for a specific question
      parameters:
      - description: Answer info
        in: body
        name: answer
        required: true
        schema:
          $ref: '#/definitions/restapi.CreateAnswerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Answer'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - CookieAuth: []
      summary: Register a new answer
      tags:
      - answer
  /api/create-question:
    post:
      consumes:
      - application/json
      description: Create a question under a specific quiz
      parameters:
      - description: Question info
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/restapi.CreateQuestionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Question'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - CookieAuth: []
      summary: Register a new question
      tags:
      - question
  /api/create-quiz:
    post:
      consumes:
      - application/json
      description: Create a quiz with name
      parameters:
      - description: Quiz info
        in: body
        name: quiz
        required: true
        schema:
          $ref: '#/definitions/restapi.CreateQuizRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Quiz'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - CookieAuth: []
      summary: Register a new quiz
      tags:
      - quiz
  /api/join-quiz:
    get:
      description: Retrieve a single quiz by Invite Code
      parameters:
      - description: Quiz Invite Code
        in: query
        name: invite
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Quiz'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a quiz by Invite Code
      tags:
      - quiz
  /api/questions:
    get:
      consumes:
      - application/json
      description: Retrieve all questions belonging to a specific quiz
      parameters:
      - description: Quiz ID
        in: query
        name: quiz_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Question'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - CookieAuth: []
      summary: Get all questions for a quiz
      tags:
      - question
  /api/questions/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a question using its unique ID
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Question'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - CookieAuth: []
      summary: Get a question by ID
      tags:
      - question
  /api/quiz/{id}:
    get:
      description: Retrieve a single quiz by its ID
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Quiz'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - CookieAuth: []
      summary: Get a quiz by ID
      tags:
      - quiz
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login with with email and password
      parameters:
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/restapi.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a existing user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a user with username, email and password
      parameters:
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/restapi.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - auth
securityDefinitions:
  CookieAuth:
    in: cookie
    name: access_token
    type: apiKey
swagger: "2.0"
